apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/dms-sms-local: "true"
        io.kompose.service: api-gateway
    spec:
      containers:
        - env:
            - name: CONSUL_ADDRESS
              value: "$CONSUL_ADDRESS"
            - name: JAEGER_ADDRESS
              value: "$JAEGER_ADDRESS"
            - name: JWT_SECRET_KEY
              value: "$JWT_SECRET_KEY"
          image: jinhong0719/dms-sms-api-gateway:$VERSION.RELEASE
          name: api-gateway
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/filebeat/log/dms-sms
              name: log-data
      restartPolicy: Always
      volumes:
        - name: log-data
          persistentVolumeClaim:
            claimName: log-data
status: {}
