apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f filebeat-docker-compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: filebeat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f filebeat-docker-compose.yml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/elk: "true"
        io.kompose.service: filebeat
    spec:
      initContainers:
        - name: initcontainer
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - chmod ugo+rwx /usr/share/filebeat/log/dms-sms
          volumeMounts:
            - mountPath: /usr/share/filebeat/log/dms-sms
              name: log-data
      containers:
        - image: elastic/filebeat:7.9.3
          name: filebeat
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/filebeat/log/dms-sms
              name: log-data
            - mountPath: /usr/share/filebeat/filebeat.yml
              name: filebeat
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: log-data
          persistentVolumeClaim:
            claimName: log-data
        - name: filebeat
          hostPath:
            path: $FILEBEAT_DIRECTORY/filebeat.yml
            type: FileOrCreate
status: {}
